apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  labels:
    app: book-import
  name: book-import-placement-1-drpc
  namespace: book-import-example
spec:
  action: Failover
  failoverCluster: secondary
  drPolicyRef:
    name: drsync5m
  placementRef:
    kind: Placements
    name: book-import-placement-1
  preferredCluster: primary
  pvcSelector:
    matchLabels:
      appname: busybox
