---
- name: Capture Book-import CPUThreshold Alert
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:
    - name: Book-import hits CPU threshold
      condition: event.alert.labels.alertname == "book-importCPUThresholdReached" and event.alert.status == "firing"
      action:
        run_job_template:
          name: Failover
          organization: Default
