---
- name: Ansible Playbook
  hosts: localhost
  tasks:
    - name: DRPlacementControl
      kubernetes.core.k8s:
        definition:
          apiVersion: ramendr.openshift.io/v1alpha1
          kind: DRPlacementControl
          metadata:
            labels:
              app: "{{ application_name }}"
            name: "{{ application_name }}-placement-1-drpc"
            namespace: "{{application_name}}-example"
          spec:
            action: Failover
            failoverCluster: secondary
            drPolicyRef:
              name: odr-policy
            placementRef:
              kind: PlacementRule
              name: "{{ application_name }}"-placement
            preferredCluster: primary
            pvcSelector:
              matchLabels:
                appname: "{{ application_name }}"
